name: final_taller_jc_env
channels:
  - conda-forge
  - defaults
# the packages that will be installed
dependencies:
  - pip=24.0
  - python=3.12
# the packages that will be installed using pip
  - pip:
      - matplotlib==3.8.4
      - pandas==2.2.2
      - plotly==5.23.0
      - scikit-learn==1.4.2
      - seaborn==0.13.2
      - streamlit==1.36.0